import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Header from "@/components/header";
// This layout file, is basically like a parent component that wraps all the pages and components in the app directory.
// It allows you to define common structure, styles, or functionality that should be shared across multiple pages.
// Good place to add nav bar and side bar
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// That's why its called a ROOT layout, and that's whay all the other pages in
//  the app directory are children of this layout.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
       
        {children}
      </body>
    </html>
  );
}
